# Generated by Django 5.0.7 on 2024-07-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_Upload_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('count', models.IntegerField(null=True)),
                ('from_date', models.CharField(max_length=100, null=True)),
                ('to_date', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
