# Generated by Django 5.0.7 on 2024-07-25 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Krima_App', '0003_push_to_pm_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ED_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Editor_push',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_length', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('sta', models.BooleanField(default=False)),
                ('Editior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Krima_App.ed_user')),
            ],
        ),
        migrations.CreateModel(
            name='Final_data_PM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('Edited_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Krima_App.editor_push')),
                ('Editior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Krima_App.ed_user')),
            ],
        ),
        migrations.CreateModel(
            name='my_Qc_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc_file', models.FileField(upload_to='qc')),
                ('from_date', models.CharField(max_length=100, null=True)),
                ('to_date', models.CharField(max_length=100, null=True)),
                ('start', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('end', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('my_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Krima_App.my_upload_file')),
            ],
        ),
        migrations.AddField(
            model_name='editor_push',
            name='qc_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Krima_App.my_qc_data'),
        ),
        migrations.CreateModel(
            name='Qc_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='my_qc_data',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Krima_App.qc_user'),
        ),
        migrations.AddField(
            model_name='editor_push',
            name='qc_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Krima_App.qc_user'),
        ),
    ]
