# Generated by Django 5.0.7 on 2024-07-25 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Krima_App', '0004_ed_user_editor_push_final_data_pm_my_qc_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_qc_data',
            name='my_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Krima_App.push_to_pm_file'),
        ),
    ]
